### ISSUE TITLE
Setup Docker DNS container

### ISSUE THREAD

**Issue by mklasen** [mklasen/alcedo-local-server#1]
Setup a container using [cytopia/bind](https://hub.docker.com/r/cytopia/bind/) that catches all `.test` requests and redirects them to the server in the local network.

`nano /etc/systemd/resolved.conf`
```
[Resolve]
DNS=127.0.0.1
FallbackDNS=192.168.2.254
#Domains=
#DNSSEC=no
#DNSOverTLS=no
#MulticastDNS=no
#LLMNR=no
#Cache=no-negative
DNSStubListener=no
#ReadEtcHosts=yes
#ResolveUnicastSingleLabel=no
```

Run `systemd-resolve --status` to confirm:
```
DNS Servers: 127.0.0.1
Fallback DNS Servers: 192.168.2.254
```

~Edit
`/etc/dhcp/dhclient.conf`
and add:
`prepend domain-name-servers 127.0.0.1;`~

docker-compose.yml
```
version: "3"

services:
  bind:
    image: cytopia/bind:0.15
    hostname: bind
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    dns:
      - 127.0.0.1
    environment:
      - WILDCARD_DNS=loc=127.0.0.1
      - DNS_FORWARDER=192.168.2.254
      - DOCKER_LOGS=1
```

1. Set router DNS to your local machine.

Certificates
- Using mkcert
- install brew,
- install mkcert..
- Change docker volume mounts, move certificates to home folder
- pre-install-cmd in composer.json that runs mkcert (turn into composer package?)
- Make sure certificate volumes are set
- Export CAROOT 
- Import on PC
- Share via Airdrop -> install on phone
